image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - pep8
  - step-1
  - step-2
  - step-3
  - step-4


cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

pep8:
  stage: pep8
  script:
    - pip install flake8
    - flake8

step_1:
  stage: step-1
  script:
    - python -m unittest test.step_1

step_2:
  stage: step-2
  script:
    - python -m unittest test.step_2

step_3:
  stage: step-3
  script:
    - python -m unittest test.step_3

step_4:
  stage: step-4
  script:
    - python -m unittest test.step_4
